//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureManagmentCore.Domains.supplies
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GPS_Tracking_Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GPS_Tracking_Car()
        {
            this.SystemComponents = new HashSet<SystemComponent>();
        }
        [Key]
        public int Carid { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public string Department { get; set; }
        public string carbnumber { get; set; }
        public string ProductCode { get; set; }
        public string EAN { get; set; }
        public string linenumber { get; set; }
        public string puk1 { get; set; }
        public string Serial { get; set; }
        public string IMEI { get; set; }
        public string status { get; set; }
        public string DriverName { get; set; }
        public string phonenumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemComponent> SystemComponents { get; set; }
    }
}
