//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureManagmentCore.Domains.supplies
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USB_Modem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USB_Modem()
        {
            this.SystemComponents = new HashSet<SystemComponent>();
        }
        [Key]
        public int USBMid { get; set; }
        public double puk { get; set; }
        public double pin { get; set; }
        public double SKU { get; set; }
        public string SIM { get; set; }
        public double IMEI { get; set; }
        public double SN { get; set; }
        public double OrderID { get; set; }
        public string Department { get; set; }
        public string DeliverableName { get; set; }
        public string NationalId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemComponent> SystemComponents { get; set; }
    }
}
