//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureManagmentCore.Domains.supplies
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VPNLeasedLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VPNLeasedLine()
        {
            this.IPAddresses = new HashSet<IPAdress>();
            this.SystemComponents = new HashSet<SystemComponent>();
        }
        [Key]
        public int lineid { get; set; }
        public string Name { get; set; }
        public string description { get; set; }
        public string phonenumber { get; set; }
        public double Orderid { get; set; }
        public string speed { get; set; }
        public string package { get; set; }
        public string Branch { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPAdress> IPAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemComponent> SystemComponents { get; set; }
    }
}
